name: .NET Core - Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: AutoModality/action-clean@1.1.0
    - uses: actions/checkout@v3.1.0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore -r linux-arm
    - name: Build
      run: dotnet build ./PickupBot/PickupBot.csproj --configuration Release --no-restore -r linux-arm
    - name: Test
      run: dotnet test --verbosity normal
